### ISSUE TITLE
There shouldn't just be one file that holds all of the models. 

### ISSUE THREAD

**Issue by tko22** [tko22/flask-boilerplate#8]
create a `models` folder, then move the Person and Email models into different files. Don't forget the __init__.py and create db instance!

**Comment by yashg5** [comment]
can you provide me an example of how to do this ??

**Comment by tko22** [comment]
right now, the path to `models.py` is `api/models.py`. It may be more modular if we moved it so we would have this structure:
- `api/`
   - `models/`
         - `__init__.py` in which `db` is initialized here.
         - `Person.py`
         - `Email.py`

I should also be able to do `from api.models import Person, Email` and import the Person **object**

**Comment by yashg5** [comment]
Got it. Thank you

**Comment by yashg5** [comment]
can you provide me examples to run test cases on post methods with authorization? that would be lot of help to my project.

**Comment by tko22** [comment]
there’s multiple ways of doing authentication so I can’t give you a specific example. Look into the test client api though. http://flask.pocoo.org/docs/1.0/api/#test-client

**Comment by tko22** [comment]
fixed
